### PR TITLE
Fixed build, added reflection config

### PR DESCRIPTION
**Pull request by hg-ms**
added pom.xml
added a new GraalVM reflection config

native image now building

### CODE REVIEW

**Comment by dalexandrov** [comment]
Still not building:


[WARNING] Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported field java.net.URL.handlers is reachable
[WARNING] To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
[WARNING] Detailed message:
[WARNING] Trace: 
[WARNING]       at parsing java.net.URL.setURLStreamHandlerFactory(URL.java:1213)
[WARNING] Call path from entry point to java.net.URL.setURLStreamHandlerFactory(URLStreamHandlerFactory): 
[WARNING]       at java.net.URL.setURLStreamHandlerFactory(URL.java:1205)
[WARNING]       at com.oracle.svm.reflect.URL_setURLStreamHandlerFactory_8b4d2aa28c41f22bcb499464d696277608a31df4_7965.invoke(Unknown Source)
[WARNING]       at java.lang.reflect.Method.invoke(Method.java:566)
[WARNING]       at com.oracle.svm.core.hub.DynamicHub.initEnumConstantsAtRuntime(DynamicHub.java:477)
[WARNING]       at com.oracle.svm.core.hub.DynamicHub.lambda$initEnumConstantsAtRuntime$1(DynamicHub.java:457)
[WARNING]       at com.oracle.svm.core.hub.DynamicHub$$Lambda$1603/0x00000007c1306440.get(Unknown Source)
[WARNING]       at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
[WARNING]       at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
[WARNING]       at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:331)
[WARNING]       at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
[WARNING] 
[WARNING] com.oracle.svm.core.util.UserError$UserException: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported field java.net.URL.handlers is reachable
[WARNING] To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
[WARNING] Detailed message:
[WARNING] Trace: 
[WARNING]       at parsing java.net.URL.setURLStreamHandlerFactory(URL.java:1213)
[WARNING] Call path from entry point to java.net.URL.setURLStreamHandlerFactory(URLStreamHandlerFactory): 
[WARNING]       at java.net.URL.setURLStreamHandlerFactory(URL.java:1205)
[WARNING]       at com.oracle.svm.reflect.URL_setURLStreamHandlerFactory_8b4d2aa28c41f22bcb499464d696277608a31df4_7965.invoke(Unknown Source)
[WARNING]       at java.lang.reflect.Method.invoke(Method.java:566)
[WARNING]       at com.oracle.svm.core.hub.DynamicHub.initEnumConstantsAtRuntime(DynamicHub.java:477)
[WARNING]       at com.oracle.svm.core.hub.DynamicHub.lambda$initEnumConstantsAtRuntime$1(DynamicHub.java:457)
[WARNING]       at com.oracle.svm.core.hub.DynamicHub$$Lambda$1603/0x00000007c1306440.get(Unknown Source)
[WARNING]       at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
[WARNING]       at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
[WARNING]       at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:331)
[WARNING]       at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
[WARNING] 
[WARNING]       at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
[WARNING]       at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
[WARNING]       at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
[WARNING]       at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
[WARNING]       at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
[WARNING]       at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[WARNING]       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[WARNING]       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[WARNING]       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[WARNING]       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[WARNING]       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[WARNING] Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported field java.net.URL.handlers is reachable
[WARNING] To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
[WARNING] Detailed message:
[WARNING] Trace: 
[WARNING]       at parsing java.net.URL.setURLStreamHandlerFactory(URL.java:1213)
[WARNING] Call path from entry point to java.net.URL.setURLStreamHandlerFactory(URLStreamHandlerFactory): 
[WARNING]       at java.net.URL.setURLStreamHandlerFactory(URL.java:1205)
[WARNING]       at com.oracle.svm.reflect.URL_setURLStreamHandlerFactory_8b4d2aa28c41f22bcb499464d696277608a31df4_7965.invoke(Unknown Source)
[WARNING]       at java.lang.reflect.Method.invoke(Method.java:566)
[WARNING]       at com.oracle.svm.core.hub.DynamicHub.initEnumConstantsAtRuntime(DynamicHub.java:477)
[WARNING]       at com.oracle.svm.core.hub.DynamicHub.lambda$initEnumConstantsAtRuntime$1(DynamicHub.java:457)
[WARNING]       at com.oracle.svm.core.hub.DynamicHub$$Lambda$1603/0x00000007c1306440.get(Unknown Source)
[WARNING]       at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
[WARNING]       at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
[WARNING]       at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:331)
[WARNING]       at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
[WARNING] 
[WARNING]       at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
[WARNING]       at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:762)
[WARNING]       ... 8 more
[WARNING] Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported field java.net.URL.handlers is reachable
[WARNING] To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
[WARNING]       at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:140)
[WARNING]       at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:123)
[WARNING]       at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:123)
[WARNING]       at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:362)
[WARNING]       at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupField(WrappedConstantPool.java:120)
[WARNING]       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupField(BytecodeParser.java:4328)
[WARNING]       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4848)
[WARNING]       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5334)
[WARNING]       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3413)
[WARNING]       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3220)
[WARNING]       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1090)
[WARNING]       at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:984)
[WARNING]       at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
[WARNING]       at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:74)
[WARNING]       at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
[WARNING]       at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
[WARNING]       at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
[WARNING]       at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
[WARNING]       at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:223)
[WARNING]       at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
[WARNING]       at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
[WARNING]       at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
[WARNING]       at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
[WARNING]       at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:434)
[WARNING]       at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:552)
[WARNING]       at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
[WARNING]       at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[WARNING]       ... 5 more
[WARNING] Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:12 min
[INFO] Finished at: 2020-11-23T13:57:18+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.helidon.build-tools:helidon-maven-plugin:2.1.2:native-image (native-image) on project microstream.example: Image generation failed, exit code: 1 -> [Help 1]
[ERROR]

**Comment by hg-ms** [comment]
Can't reproduce the error above with GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)
Tried with a colleague and he could build it without problem too.

Did you do any modification to the example?

**Comment by zdenek-jonas** [comment]
I have tried to build it with docker graalvm image. The docker just need more RAM for build. 
Then install maven, just dockerfile:

```
FROM oracle/graalvm-ce:20.3.0-java11

ARG MAVEN_VERSION=3.6.3
ARG USER_HOME_DIR="/root"
ARG SHA=c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
  && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
  && echo "${SHA}  /tmp/apache-maven.tar.gz" | sha512sum -c - \
  && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
  && rm -f /tmp/apache-maven.tar.gz \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn
  
ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"
```
then 
`docker build .`

then:
`docker run -it -v $(pwd):/opt1 "imageId" /bin/bash`

Inside the docker install native image
`gu install native-image`

go to the project and just run:
`mvn clean install -Pnative-image`

**Comment by dalexandrov** [comment]
> Can't reproduce the error above with GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)
> Tried with a colleague and he could build it without problem too.
> 
> Did you do any modification to the example?

is this on mac ?

**Comment by hg-ms** [comment]
> 
> 
> > Can't reproduce the error above with GraalVM Version 20.3.0 (Java Version 11.0.9+10-jvmci-20.3-b06)
> > Tried with a colleague and he could build it without problem too.
> > Did you do any modification to the example?
> 
> is this on mac ?

 johny2000uwb tested on Linux,
I tested on Win10

**Comment by zdenek-jonas** [comment]
I will try to build this today with mac.

**Comment by zdenek-jonas** [comment]
Under mac: alles sieht gut aus
image

**Comment by dalexandrov** [comment]
Complete reinstall of GraalVM and native-image fixed everything! Thank you! Sorry to bother..

**Comment by hg-ms** [comment]
> 
> 
> Complete reinstall of GraalVM and native-image fixed everything! Thank you! Sorry to bother..

You’re welcome. Good to know that you could solve the Problem.

**Pull request merged**
